name: squishy
version: '0.1.0.0'
category: Web
author: Sean Lee
maintainer: freshdried@gmail.com
copyright: 2017 Sean Lee
license: BSD3
github: sleexyz/squishy
extra-source-files:
- README.md
library:
  source-dirs: src
  dependencies:
  - base >=4.7 && <5
  - attoparsec
  - text
  - unordered-containers
  - mtl
executables:
  letlang:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - letlang
tests:
  letlang-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - letlang
    - hspec
